{{- if .Values.frontend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tinyolly.frontend.serviceAccountName" . }}
  labels:
    {{- include "tinyolly.frontend.labels" . | nindent 4 }}
  {{- with .Values.frontend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
