{{- if .Values.otlpReceiver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tinyolly.otlpReceiver.serviceAccountName" . }}
  labels:
    {{- include "tinyolly.otlpReceiver.labels" . | nindent 4 }}
  {{- with .Values.otlpReceiver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
