{{- if .Values.ui.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tinyolly.ui.serviceAccountName" . }}
  labels:
    {{- include "tinyolly.ui.labels" . | nindent 4 }}
  {{- with .Values.ui.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
