{{- if .Values.webui.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tinyolly.webui.serviceAccountName" . }}
  labels:
    {{- include "tinyolly.webui.labels" . | nindent 4 }}
  {{- with .Values.webui.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
