apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo-routes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "70"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  source:
    repoURL: 'https://github.com/tinyolly/tinyolly.git'
    path: .kind/modules/tinyolly/k8s-manifests/otel-demo
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: otel-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
