apiVersion: v1
kind: Service
metadata:
  name: demo-frontend
  namespace: { { .Values.global.namespace } }
  labels: { { - include "tinyolly-demos.frontend.labels" . | nindent 4 } }
spec:
  type: { { .Values.frontend.service.type } }
  ports:
    - port: { { .Values.frontend.service.port } }
      targetPort: http
      protocol: TCP
      name: http
    - port: 8000
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    { { - include "tinyolly-demos.frontend.selectorLabels" . | nindent 4 } }
