{{- if .Values.gatewayCollector.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway
  labels:
    {{- include "tinyolly.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-gateway
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "services", "endpoints"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
{{- end }}
