apiVersion: v1
kind: Service
metadata:
  name: {{ include "tinyolly.ui.name" . }}
  labels:
    {{- include "tinyolly.ui.labels" . | nindent 4 }}
  {{- with .Values.ui.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ui.service.type }}
  {{- if and (eq .Values.ui.service.type "NodePort") .Values.ui.service.nodePort }}
  ports:
  - port: {{ .Values.ui.service.port }}
    targetPort: {{ .Values.ui.service.targetPort }}
    protocol: TCP
    name: http
    nodePort: {{ .Values.ui.service.nodePort }}
  {{- else }}
  ports:
  - port: {{ .Values.ui.service.port }}
    targetPort: {{ .Values.ui.service.targetPort }}
    protocol: TCP
    name: http
  {{- end }}
  selector:
    {{- include "tinyolly.ui.selectorLabels" . | nindent 4 }}
