apiVersion: v1
kind: Service
metadata:
  name: ai-agent
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ollyscale-otel-agent.agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.agent.service.type }}
  selector:
    {{- include "ollyscale-otel-agent.agent.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.agent.service.port }}
      targetPort: 8000
      name: http
