{{- if .Values.agentCollector.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent
  namespace: {{ .Values.agentCollector.namespace }}
  labels:
    {{- include "ollyscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-agent
{{- end }}
