{{- if .Values.ebpfAgent.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ollyscale.fullname" . }}-ebpf-agent
  labels:
    {{- include "ollyscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: ebpf-agent
rules:
  # Need to read node information
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  # Need to read pod information to map PIDs to services
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "watch", "list"]
  # Need access to services for service discovery
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
{{- end }}
