{{- if .Values.gatewayCollector.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway
  labels:
    {{- include "ollyscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gateway
subjects:
  - kind: ServiceAccount
    name: gateway
    namespace: {{ .Values.gatewayCollector.namespace }}
{{- end }}
