{{- if .Values.gatewayCollector.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
  namespace: {{ .Values.gatewayCollector.namespace }}
  labels:
    {{- include "ollyscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-gateway
{{- end }}
