apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ollyscale.fullname" . }}-migration
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ollyscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
automountServiceAccountToken: false
