{{- if .Values.opampServer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ollyscale.opampServer.serviceAccountName" . }}
  labels:
    {{- include "ollyscale.opampServer.labels" . | nindent 4 }}
  {{- with .Values.opampServer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
